HMC2/config/routes.rb
Rails.application.routes.draw do
  resources :blocks

  resources :polls

  get 'dashboard/index'

  devise_for :users
  resources :users
  root 'dashboard#index'

  resources :polls do
  member do
    get 'show'
  end
    end

end

HMC2/app/models/block.rb
class Block < ActiveRecord::Base
  belongs_to :poll
end

HMC2/app/models/poll.rb
class Poll < ActiveRecord::Base
  belongs_to :user
  has_many :blocks
end

HMC2/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :polls

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

HMC2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :authenticate_user!
  protect_from_forgery with: :exception

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :uname
  end
end

HMC2/app/controllers/blocks_controller.rb
class BlocksController < ApplicationController
  before_action :set_block, only: [:show, :edit, :update, :destroy]

  def index
    @blocks = Block.all
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @block }
    end
  end

  def show
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @block }
    end
  end

  def new
    @block = Block.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @block }
    end
  end

  def edit
  end

  def create
    @block = Block.new(block_params)
    @block.save
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @block }
    end
  end

  def update
    @block.update(block_params)
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @block }
    end
  end

  def destroy
    @block.destroy
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @block }
    end
  end

  private
    def set_block
      @block = Block.find(params[:id])
    end

    def block_params
      params.require(:block).permit(:head, :description, :image, :poll_id)
    end
end

HMC2/app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

HMC2/app/controllers/polls_controller.rb
class PollsController < ApplicationController
  before_action :set_poll, only: [:show, :edit, :update, :destroy]

  def index
    @polls = Poll.all
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @poll }
    end
  end

  def show
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @poll }
    end
  end

  def new
    @poll = Poll.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @poll }
    end
  end

  def edit
  end

  def create
    @poll = Poll.new(poll_params)
    @poll.user_id = current_user.user_id
    if @poll.save
      redirect_to "dashboard#index"
    else 
      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @poll }
      end
    end
  end

  def update
    @poll.update(poll_params)
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @poll }
    end
  end

  def destroy
    @poll.destroy
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @poll }
    end
  end

  private
    def set_poll
      @poll = Poll.find(params[:id])
    end

    def poll_params
      params.require(:poll).permit(:title, :user_id)
    end
end

HMC2/app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
	private
	def sign_up_params
    params.require(:user).permit(:uname, :email, :password, :password_confirmation)
  end
 
  def account_update_params
    params.require(:user).permit(:uname, :email, :password, :password_confirmation, :current_password)
  end
end

HMC2/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  def show
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  def new
    @user = User.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    @user.save
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  def update
    @user.update(user_params)
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:user_id, :uname)
    end
end

HMC2/app/helpers/application_helper.rb
module ApplicationHelper
end

HMC2/app/helpers/blocks_helper.rb
module BlocksHelper
end

HMC2/app/helpers/dashboard_helper.rb
module DashboardHelper
end

HMC2/app/helpers/polls_helper.rb
module PollsHelper
end

HMC2/app/helpers/registrations_helper.rb
module RegistrationsHelper
end

HMC2/app/helpers/users_helper.rb
module UsersHelper
end

HMC2/app/views/blocks/_form.html.erb
<%= form_for(@block) do |f| %>
  <% if @block.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@block.errors.count, "error") %> prohibited this block from being saved:</h2>

      <ul>
      <% @block.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :head %><br>
    <%= f.text_field :head %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :poll_id %><br>
    <%= f.text_field :poll_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

HMC2/app/views/blocks/edit.html.erb
<h1>Editing block</h1>

<%= render 'form' %>

<%= link_to 'Show', @block %> |
<%= link_to 'Back', blocks_path %>

HMC2/app/views/blocks/index.html.erb
<h1>Listing blocks</h1>

<table>
  <thead>
    <tr>
      <th>Head</th>
      <th>Description</th>
      <th>Image</th>
      <th>Poll</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blocks.each do |block| %>
      <tr>
        <td><%= block.head %></td>
        <td><%= block.description %></td>
        <td><%= block.image %></td>
        <td><%= block.poll %></td>
        <td><%= link_to 'Show', block %></td>
        <td><%= link_to 'Edit', edit_block_path(block) %></td>
        <td><%= link_to 'Destroy', block, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Block', new_block_path %>

HMC2/app/views/blocks/new.html.erb
<h1>New block</h1>

<%= render 'form' %>

<%= link_to 'Back', blocks_path %>

HMC2/app/views/blocks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Head:</strong>
  <%= @block.head %>
</p>

<p>
  <strong>Description:</strong>
  <%= @block.description %>
</p>

<p>
  <strong>Image:</strong>
  <%= @block.image %>
</p>

<p>
  <strong>Poll:</strong>
  <%= @block.poll %>
</p>

<%= link_to 'Edit', edit_block_path(@block) %> |
<%= link_to 'Back', blocks_path %>

HMC2/app/views/dashboard/index.html.erb
<div class="container-fluid">
<div class="row" style="background-color:Aqua;text-align:center;" >
<h2><%= current_user.email.split('@')[0] %>'s dashboard</h2>
</div>
<div class="row">
<p> HI!  </p>
<%= link_to 'Logout', destroy_user_session_path , :method => :delete %><br/>
<%= link_to 'Create New Poll', new_poll_path %> <br/>
Polls created so far:-<br/>
<ul>
   <% Poll.all.each do |poll| %>
    <% if poll.user_id == current_user.id %>
    <% @p = poll.title %>
    <li> <%= link_to "p" ,poll %>  <%=link_to "delete poll", poll.delete %></li>
    <% end %>
   <% end %>
</ul>
</tbody>
</div>
</div>

HMC2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HMC2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= yield %>

</body>
</html>

HMC2/app/views/polls/_form.html.erb
<%= form_for(@poll) do |f| %>
  <% if @poll.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@poll.errors.count, "error") %> prohibited this poll from being saved:</h2>

      <ul>
      <% @poll.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  
  <div> <p> Enter Fields: </p>
  
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

HMC2/app/views/polls/edit.html.erb
<h1>Editing poll</h1>

<%= render 'form' %>

<%= link_to 'Show', @poll %> |
<%= link_to 'Back', polls_path %>

HMC2/app/views/polls/index.html.erb
<h1>Listing polls</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @polls.each do |poll| %>
      <tr>
        <td><%= poll.title %></td>
        <td><%= poll.user %></td>
        <td><%= link_to 'Show', poll %></td>
        <td><%= link_to 'Edit', edit_poll_path(poll) %></td>
        <td><%= link_to 'Destroy', poll, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Poll', new_poll_path %>

HMC2/app/views/polls/new.html.erb
<h1>New poll</h1>

<%= render 'form' %>

<%= link_to 'Back', polls_path %>

HMC2/app/views/polls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @poll.title %>
</p>

<p>
  <strong>User:</strong>
  <%= @poll.user %>
</p>

<%= link_to 'Edit', edit_poll_path(@poll) %> |
<%= link_to 'Back', polls_path %>

HMC2/app/views/user/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

HMC2/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :uname %><br>
    <%= f.text_field :uname %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

HMC2/app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

HMC2/app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Uname</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.user_id %></td>
        <td><%= user.uname %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

HMC2/app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

HMC2/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user.user_id %>
</p>

<p>
  <strong>Uname:</strong>
  <%= @user.uname %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>